### ISSUE TITLE
add composer, symfony-cli

### ISSUE THREAD

**Issue by drupol** [samuela/nixpkgs-upkeep#11]
Hello,

Do you think it would be possible to add:

* composer ([website](https://getcomposer.org/), [nix package](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=composer))
* symfony-cli ([website](https://github.com/symfony/cli), [nix-package](https://search.nixos.org/packages?channel=unstable&show=symfony-cli&from=0&size=50&sort=relevance&query=symfony-cli))

Thanks!

**Comment by samuela** [comment]
Sure, I think those would be pretty straightforward. I'm happy to accept PRs for packages that others are interested in. See https://github.com/samuela/nixpkgs-upkeep/pull/6 for a good example of how this works. If you have any questions about the PR process just let me know!
