### ISSUE TITLE
Bot disabled after inactivity

### ISSUE THREAD

**Issue by Synthetica9** [samuela/nixpkgs-upkeep#15]
After 60 days of inactivity, the bot gets disabled. I hope that posting this issue will cause it to go away, but otherwise: maybe push an empty commit? Not sure what counts as activity to github actions

**Comment by samuela** [comment]
Yeah, GitHub sent me an email about this with a big green button that said "Re-enable actions", but clicking on it apparently did nothing at all. I'll push an empty commit to force it back into action.

**Comment by samuela** [comment]
Should be fixed in https://github.com/samuela/nixpkgs-upkeep/commit/ebcae1ecd41ba5715b3670f0c1698509251127d1
