### ISSUE TITLE
vscode does not update

### ISSUE THREAD

**Issue by TethysSvensson** [samuela/nixpkgs-upkeep#21]

**Comment by samuela** [comment]
vscode updater is working as of https://github.com/samuela/nixpkgs-upkeep/actions/runs/4088912551/jobs/7051062058

**Comment by TethysSvensson** [comment]
Probably because vscode got updated in nixokgs.

It wasn't working yesterday: https://github.com/samuela/nixpkgs-upkeep/actions/runs/4079807666/jobs/7031572255

**Comment by samuela** [comment]
no it was failing bc my fork of nixpkgs was out of date and there were upstream changes to protected files. when that happens it is unable to push the branch to my fork.

**Comment by samuela** [comment]
see https://github.com/samuela/nixpkgs-upkeep#faq for more info

**Comment by TethysSvensson** [comment]
Okay, thanks. Sorry for wasting your time then. 😅
