### ISSUE TITLE
Don't assign issues to others

### ISSUE THREAD

**Issue by dotlambda** [samuela/nixpkgs-upkeep#22]

**Comment by samuela** [comment]
Issues are only assigned to package maintainers when those packages fail to build. Would you prefer not to be assigned issues when packages you maintain are broken?

**Comment by SuperSandro2000** [comment]
I would prefer to just be pinged. I maintain way to many packages and some build failures I just outright ignore or immediately mark broken eg. darwin in 90% of the cases.

**Comment by samuela** [comment]
Gotcha gotcha, ok should be fixed in https://github.com/samuela/nixpkgs-upkeep/commit/b75fe87a0383b20f5335382133b86e67f63cd858!

**Comment by SuperSandro2000** [comment]
I think this should be generally disabled or be opt in. Especially dotlambdas last comment applies generally.

**Comment by phanirithvij** [comment]
mention instead of assign
